qatrack/qa/urls.py
from django.conf.urls.defaults import patterns, include, url

import views
from qatrack.decorators import custom_permission_required as cpr
from qatrack.qa import api
from tastypie.api import Api

v1_api = Api(api_name="v1")
resources = [
    api.TestListResource(),
    api.TestResource(),
    api.TestInstanceResource(),
    api.TestListInstanceResource(),
    api.ValueResource(),
    api.FrequencyResource(),
    api.StatusResource(),
    api.ReferenceResource(),
    api.CategoryResource(),
    api.ToleranceResource(),
    api.UnitResource(),
    api.ModalityResource(),
    api.UnitTypeResource(),
    api.GroupResource(),
]
for resource in resources:
    v1_api.register(resource)

can_view_history = cpr("qa.can_view_history")
can_edit = cpr("qa.change_testinstance")

urlpatterns = patterns('',

                       url(r"^(?P<data>data/)?$", views.UTCList.as_view(), name="all_lists"),

                       # view for composite calculations via ajax
                       url(r"^composite/$", views.CompositeCalculation.as_view(), name="composite"),


                       # api urls
                       url(r"^api/", include(v1_api.urls)),

                       url(r"^charts/$", can_view_history(views.ChartView.as_view()), name="charts"),
                       url(r"^charts/export/$", can_view_history(views.ExportToCSV.as_view()), name="export_data"),
                       url(r"^charts/data/$", can_view_history(views.BasicChartData.as_view()), name="chart_data"),
                       # generating control chart images
                       url(r"^charts/control_chart.png$", can_view_history(views.ControlChartImage.as_view()), name="control_chart"),

                       # overall program status
                       url(r"^review/$", can_view_history(views.Overview.as_view()), name="overview"),
                       url(r"^review/due-dates/$", can_view_history(views.DueDateOverview.as_view()), name="overview_due_dates"),

                       # review utc's
                       url(r"^review/all/(?P<data>data/)?$", can_edit(views.UTCReview.as_view()), name="review_all"),
                       url(r"^review/utc/(?P<pk>\d+)/(?P<data>data/)?$", can_edit(views.UTCInstances.as_view()), name="review_utc"),
                       url(r"^review/frequency/$", can_edit(views.ChooseFrequencyForReview.as_view()), name="choose_review_frequency"),
                       url(r"^review/frequency/(?P<frequency>[/\w-]+?)/(?P<data>data/)?$", can_edit(views.UTCFrequencyReview.as_view()), name="review_by_frequency"),
                       url(r"^review/unit/$", can_edit(views.ChooseUnitForReview.as_view()), name="choose_review_unit"),
                       url(r"^review/unit/(?P<unit_number>[/\d]+)/(?P<data>data/)?$", can_edit(views.UTCUnitReview.as_view()), name="review_by_unit"),

                       # test list instances
                       url(r"^session/details/(?P<data>data/)?$", can_edit(views.TestListInstances.as_view()), name="complete_instances"),
                       url(r"^session/details/(?P<pk>\d+)/$", can_edit(views.ReviewTestListInstance.as_view()), name="review_test_list_instance"),
                       url(r"^session/unreviewed/(?P<data>data/)?$", can_view_history(views.Unreviewed.as_view()), name="unreviewed"),
                       url(r"^session/in-progress/(?P<data>data/)?$", views.InProgress.as_view(), name="in_progress"),
                       url(r"^session/edit/(?P<pk>\d+)/$", views.EditTestListInstance.as_view(), name="edit_tli"),


                       url(r"^unit/$", views.ChooseUnit.as_view(), name="choose_unit"),
                       url(r"^utc/perform/(?P<pk>\d+)/$", views.PerformQA.as_view(), name="perform_qa"),

                       url(r"^unit/(?P<unit_number>[/\d]+)/frequency/(?P<frequency>[/\w-]+?)/(?P<data>data/)?$", views.UnitFrequencyList.as_view(), name="qa_by_frequency_unit"),
                       url(r"^unit/(?P<unit_number>[/\d]+)/(?P<data>data/)?$", views.UnitList.as_view(), name="qa_by_unit"),

                       url(r"^frequency/(?P<frequency>[/\w-]+)/unit/(?P<unit_number>[/\d]+)/(?P<data>data/)?$", views.UnitFrequencyList.as_view(), name="qa_by_unit_frequency"),
                       url(r"^frequency/(?P<frequency>[/\w-]+?)/(?P<data>data/)?$", views.FrequencyList.as_view(), name="qa_by_frequency"),

                       )

qatrack/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.base import TemplateView

from django.contrib import admin
admin.autodiscover()

import settings

urlpatterns = patterns('',

    url(r'^$', TemplateView.as_view(template_name="homepage.html"), name="home"),

    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': settings.LOGIN_URL}),

    url(r'^accounts/', include('registration.urls')),

    url(r'^qa/', include('qatrack.qa.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('genericdropdown.urls')),

)

qatrack/accounts/models.py
from django.conf import settings

from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
from django.dispatch import receiver


#----------------------------------------------------------------------
@receiver(post_save,sender=User)
def add_to_default_groups(sender,instance,created,**kwargs):
    """
    if any default groups are defined in settings the user will
    be added to them.
    """

    if created:
        group_names = getattr(settings,"DEFAULT_GROUP_NAMES",[])

        for group_name in group_names:

            group,_ = Group.objects.get_or_create(name=group_name)
            instance.groups.add(group)
            instance.save()

qatrack/contacts/models.py
from django.db import models


#============================================================================
class Contact(models.Model):
    """basic contact number"""
    name = models.CharField(max_length=256)
    number = models.CharField(max_length=256)
    description = models.TextField()

    #----------------------------------------------------------------------
    def __unicode__(self):
        return "%s : %s " %(self.name,self.number)

qatrack/notifications/models.py
from django.db import models
from django.contrib.auth.models import Group, User

# this import has to be here so that the signal handlers get registered
import handlers


TOLERANCE = 10
ACTION = 20

WARNING_LEVELS = (
    (TOLERANCE, "Notify on Tolerance or Action"),
    (ACTION, "Notify on Test at Action level only"),
)

#============================================================================


class NotificationSubscription(models.Model):

    group = models.ForeignKey(Group, unique=True)

    warning_level = models.IntegerField(choices=WARNING_LEVELS)

    #----------------------------------------------------------------------
    def __unicode__(self):
        return "<NotificationSubscription(%s)>" % self.group.name

qatrack/theme_bootstrap/models.py
# This file is intentionally left blank to allow Django to load the app.

qatrack/units/models.py
from django.db import models
from django.utils.translation import ugettext as _

PHOTON = "photon"
ELECTRON = "electron"

#==========================================================================


class UnitType(models.Model):
    """Radiation Device Type

    Stores a device type for grouping individual :model:`unit`s together.
    For example, your Elekta Linacs might form one group, and your Tomo's
    another.

    TODO: improve model types
    """

    name = models.CharField(max_length=50, help_text=_("Name for this unit type"))
    vendor = models.CharField(max_length=50, help_text=_("e.g. Elekta"))
    model = models.CharField(max_length=50, help_text=_("Optional model name for this group"), null=True, blank=True)

    class Meta:
        unique_together = [("name", "model")]

    #---------------------------------------------------------------------------
    def __unicode__(self):
        """Display more descriptive name"""
        return "<UnitType(%s)>" % self.name

#============================================================================


class Modality(models.Model):
    """Treatment modalities

    defines available treatment modalities for a given :model:`unit1`

    """

    type_choices = ((PHOTON, "Photon"), (ELECTRON, "Electron"),)
    type = models.CharField(_("Treatement modality type"), choices=type_choices, max_length=20)
    energy = models.FloatField(help_text=_("Nominal energy (in MV for photons and MeV for electrons"))

    class Meta:
        verbose_name_plural = "Modalities"
        unique_together = [("type", "energy")]

    #---------------------------------------------------------------------------
    def __unicode__(self):
        if self.type == "photon":
            unit, particle = "MV", "Photon"
        else:
            unit, particle = "MeV", "Electron"
        return "<Modality(%.2f%s,%s)>" % (self.energy, unit, particle)

# class UnitManager(models.Manager):
    #---------------------------------------------------------------------------
#    def get_query_set(self):
#        return super(UnitManager,self).get_query_set().select_related("type")

#============================================================================


class Unit(models.Model):
    """Radiation devices

    Stores a single radiation device (e.g. Linac, Tomo unit, Cyberkinfe etc.)

    """

    number = models.PositiveIntegerField(null=False, unique=True, help_text=_("A unique number for this unit"))
    name = models.CharField(max_length=256, help_text=_("The display name for this unit"))
    serial_number = models.CharField(max_length=256, null=True, blank=True, help_text=_("Optional serial number"))
    location = models.CharField(max_length=256, null=True, blank=True, help_text=_("Optional location information"))
    install_date = models.DateField(null=True, blank=True, help_text=_("Optional install date"))

    type = models.ForeignKey(UnitType)

    modalities = models.ManyToManyField(Modality)
    # objects = UnitManager()

    class Meta:
        ordering = ["number"]

    #----------------------------------------------------------------------
    def __unicode__(self):
        return self.name

qatrack/notifications/views.py
# Create your views here.

qatrack/units/views.py
# Create your views here.

qatrack/templates/units/unittype_choose_for_review.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% block head_title %}Choose Unit for Review{% endblock %}

{% block body %}
<div class="row-fluid">
    <div class="span12">
        <h2>Review QA By Unit</h3>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <em>Choose a unit below to review its QA Data</em>
    </div>
</div>



{% for unit_type in unit_types %}
    <div class="row-fluid row-spacer">
        <div class="span12">

            <h4 class="header-spacer">{{unit_type.name}}</h4>
            <div class="btn-group" style="float:left">
                <button class="btn top-level"><a href="{% url choose_review_unit %}{% for unit in unit_type.unit_set.all %}{{unit.number}}/{%endfor%}">All</a></button>

                {% for unit in unit_type.unit_set.all %}
                    <button class="btn top-level"><a href="{% url review_by_unit unit_number=unit.number %}">{{unit.name}}</a></button>
                {% endfor %}
            </div>
        </div>
    </div>
{% endfor %}
<script type="text/javascript">
    $(".btn.top-level").click(function(){
        window.location = $(this).find("a").attr("href");
    });
</script>

{% endblock %}

qatrack/templates/units/unittype_list.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% block head_title %}Choose Unit{% endblock %}

{% block body %}
<div class="row-fluid">
    <div class="span12">
        <h2>Choose a Unit to Perform QA On</h3>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        Click a button to perform QA for one of the units below.
    </div>
</div>

    {% for unit_type in unit_types %}
        <div class="row-fluid row-spacer">
            <div class="span12">

                <h4 class="header-spacer">{{unit_type.name}}</h4>
                {% for unit in unit_type.unit_set.all %}
                    {% if not perms.qa.can_choose_frequency %}
                            <a class="btn" href="{% url qa_by_unit unit_number=unit.number %}">{{unit.name}}</a>
                    {% else %}
                        <div class="btn-group" style="float:left">
                            <button class="btn top-level"><a href="{% url qa_by_unit unit_number=unit.number %}">{{unit.name}}</a></button>
                            <button class="btn dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                {% for freq in QA_FREQUENCIES %}
                                <li>
                                    <a href="{% url qa_by_frequency_unit frequency=freq.0 unit_number=unit.number %}">{{unit.name}} &mdash; {{freq.1}}</a>
                                </li>
                                {% endfor %}
                                <li>
                                    <a href="{% url qa_by_frequency_unit frequency="ad-hoc" unit_number=unit.number %}">{{unit.name}} &mdash; <em>Ad-Hoc</em></a>
                                </li>
                            </ul>
                        </div>
                    {% endif %}

                {% endfor %}
            </div>
        </div>

    {% endfor %}
    <script type="text/javascript">
        $(".btn.top-level").click(function(){
            window.location = $(this).find("a").first().attr("href");
        });
    </script>

{% endblock %}